[agent]
    interval = "20s"
    round_interval = true
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    collection_jitter = "0s"
    flush_interval = "10s"
    flush_jitter = "0s"
    precision = ""
    debug = true
    quiet = false
    hostname = ""
    omit_hostname = false

#############################################################
#                   OUTPUT PLUGINS                          #
#############################################################
[[outputs.influxdb]]
    urls = [ "https://influxdb:8086" ]

    database = "edge"

    skip_database_creation = false

    timeout = "5s"
    username = "${INFLUXDB_USER}"
    password = "${INFLUXDB_USER_PASSWORD}"
    ## Use TLS but skip chain & host verification
    insecure_skip_verify = true


##################################################################
#                   INPUT PLUGINS                                #
##################################################################

[[inputs.mqtt_consumer]]

    servers = [ "ssl://mosquitto:8883" ]

    # Topics to subscribe to:
    topics = [
        "test/#"
    ]

    # Connection timeout
    connection_timeout = "30s"

    username = "${TG_MOSQUITTO_USERNAME}"
    password = "${TG_MOSQUITTO_PASSWORD}"

    ## Use TLS but skip chain & host verification
    # Use Certificates if `require_certificate true` in `mosquitto.conf` file
    tls_ca = "/etc/telegraf/ca_root.cert.pem"
    tls_cert = "/etc/telegraf/mqtt-client.cert.pem"
    tls_key = "/etc/telegraf/mqtt-client.key.pem"
    ## Use TLS but skip chain & host verification
    insecure_skip_verify = true

    data_format = "json"